
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SupunK
 */
public class UserDetails extends javax.swing.JFrame {

        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
        
    public UserDetails() {
        initComponents();
        
        con = DatabaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        institute = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnSubmit1 = new javax.swing.JButton();
        btnBackUserDetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setMinimumSize(new java.awt.Dimension(880, 560));
        jPanel2.setPreferredSize(new java.awt.Dimension(860, 580));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS");
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(28, 396, 163, 37);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER DETAILS");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(469, 20, 273, 37);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER ID");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(29, 79, 162, 37);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FIRST NAME");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(28, 136, 163, 37);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LAST NAME");
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(28, 200, 163, 37);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AGE");
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(28, 265, 163, 37);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("INSTITUTE");
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9);
        jLabel9.setBounds(28, 332, 163, 37);

        userid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(userid);
        userid.setBounds(247, 78, 237, 34);

        firstname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(firstname);
        firstname.setBounds(247, 135, 237, 34);

        age.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(age);
        age.setBounds(247, 264, 237, 34);

        institute.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(institute);
        institute.setBounds(247, 331, 237, 34);

        lastname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(lastname);
        lastname.setBounds(247, 199, 237, 34);

        address.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel2.add(address);
        address.setBounds(247, 395, 237, 34);

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit);
        btnSubmit.setBounds(680, 430, 160, 36);

        btnSubmit1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSubmit1.setText("SHOW MY DETAILS");
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit1);
        btnSubmit1.setBounds(530, 210, 330, 82);

        btnBackUserDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBackUserDetails.setText("Back");
        btnBackUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUserDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnBackUserDetails);
        btnBackUserDetails.setBounds(680, 360, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_purple.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try{
            stmt = (Statement) con.createStatement();
            int sId = Integer.parseInt(userid.getText());
            String sFname = firstname.getText();
            String sLname = lastname.getText();
            int sAge = Integer.parseInt(age.getText());
            String sInstitute = institute.getText();
            String sAddress = address.getText();
            
            String query = "INSERT INTO userdetails (userid, firstname,lastname, age, institute, address) VALUES (?,?,?,?,?,?)";
            PreparedStatement preparedStmt = con.prepareStatement(query);
            
            preparedStmt.setInt(1, sId);
            preparedStmt.setString(2, sFname);
            preparedStmt.setString(3, sLname);
            preparedStmt.setInt(4,sAge);
            preparedStmt.setString(5, sInstitute);
            preparedStmt.setString(6,sAddress);
            preparedStmt.execute();
            
            JOptionPane.showMessageDialog(null, "ADDED");
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
        try{
            stmt = (Statement) con.createStatement();
            int sId = Integer.parseInt(userid.getText());
            String query = "SELECT * FROM userdetails";
            rs = stmt.executeQuery(query);
            while(rs.next()){
                if(sId == rs.getInt("userid")){
                    userid.setText(String.format("%s",rs.getInt("userid")));
                    firstname.setText(rs.getString("firstname"));
                    lastname.setText(rs.getString("lastname"));
                    age.setText(String.format("%s",rs.getInt("age")));
                    institute.setText(rs.getString("institute"));
                    address.setText(rs.getString("address"));
                }
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnSubmit1ActionPerformed

    private void btnBackUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUserDetailsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_btnBackUserDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JButton btnBackUserDetails;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField institute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
